name: Build NekoBoot UEFI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev iasl git python3-distutils python3-pip

    - name: Set EDK2 Environment
      run: |
        cd edk2
        export WORKSPACE=$(pwd)
        export EDK_TOOLS_PATH=$WORKSPACE/BaseTools
        export CONF_PATH=$WORKSPACE/Conf

    - name: Build BaseTools
      run: |
        cd edk2/BaseTools
        chmod +x Build.sh
        ./Build.sh

    - name: Build NekoBoot
      run: |
        cd edk2
        source edksetup.sh
        build -p NekoPlatform/NekoPlatform.dsc -a X64 -b DEBUG -t GCC5

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: NekoBoot-Build
        path: Build