name: Build NekoBoot EFI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential uuid-dev iasl git python3 python3-pip

      - name: Clone EDK2
        run: |
          git clone https://github.com/tianocore/edk2.git
          cd edk2
          git submodule update --init --recursive

      - name: Setup EDK2 environment
        run: |
          cd edk2
          source edksetup.sh

      - name: Build NekoBoot EFI
        run: |
          cd edk2
          build -p ../NekoBoot/NekoPlatform/NekoPlatform.dsc -a X64 -b DEBUG

      - name: Upload EFI artifact
        uses: actions/upload-artifact@v4
        with:
          name: NekoBoot-EFI
          path: Build/DEBUG_GCC5/X64/*.efi