name: Build NekoBoot EFI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential uuid-dev iasl git python3

      - name: Clone and build with EDK2
        run: |
          git clone https://github.com/tianocore/edk2.git
          cd edk2
          git submodule update --init --recursive

          # Build BaseTools (THIS CREATES `build`)
          make -C BaseTools

          # Setup environment (MUST be same shell)
          source edksetup.sh
          export PATH=$PWD/BaseTools:$PATH

          # Sanity check
          which build

          # Build your platform
          build -p ../NekoBoot/NekoPlatform/NekoPlatform.dsc -a X64 -b DEBUG

      - name: Upload EFI artifact
        uses: actions/upload-artifact@v4
        with:
          name: NekoBoot-EFI
          path: edk2/Build/**/X64/*.efi